DEBUG = 1 # 0 - disabled, 1 - enabled


implicitly_wait = 4.5
explicit_wait = 180
upload_wait = 180

[delays]
# Delay ranges for different types of actions (in seconds)
action_min = 1.0
action_max = 3.0
# Longer delay between major actions
major_action_min = 3.0
major_action_max = 7.0
# Typing simulation delay range (in seconds)
typing_min = 0.1
typing_max = 0.3

[paths]
main = "https://www.instagram.com/"
login = "https://www.instagram.com/"
upload = 0

signup_email = "https://www.instagram.com/accounts/emailsignup/"

[selectors]

    [selectors.register]

    # Русские и английские варианты кнопки принятия всех cookies
    accept_cookies = "//button[contains(text(), 'Разрешить все cookie')] | //button[text()='Allow all cookies'] | //button[contains(@class, '_asz1') and contains(text(), 'Разрешить')] | //button[contains(@class, '_asz1') and contains(text(), 'Allow')]"
    
    # Альтернативные селекторы для кнопки принятия cookies
    alternate_accept_cookies = "//div[contains(text(), 'Разрешить все cookie') and @tabindex='0'] | //div[text()='Allow all cookies' and @tabindex='0'] | //*[contains(@class, '_a9--') and contains(@class, '_asz1')] | //button[@tabindex='0' and contains(text(), 'Разрешить все')]"

    email_field = "//input[@name=\"emailOrPhone\"]"
    password_field = "//input[@name='password']"
    full_name_field = "//input[@name='fullName']"
    username_field = "//input[@name='username']"

    next_button = "//button[text()='Next']"

    [selectors.login]
    username_field = "//input[@name='email'] | //input[@name='username'] | //input[@name='emailOrPhone']"
    password_field = "//input[@name='pass'] | //input[@name='password'] | //input[@type='password']"
    login_button = "//button[contains(text(), 'Войти') and not(@aria-disabled='true')] | //button[contains(text(), 'Log in') and not(@aria-disabled='true')] | //div[@role='button' and contains(text(), 'Войти') and not(@aria-disabled='true')] | //div[@role='button' and contains(text(), 'Log in') and not(@aria-disabled='true')]"
    alternate_login_button = "//button[@type='submit'] | //div[contains(@class, 'eiCW-')]//*[text()='Log in']"
    log_in_btn = "//div[text()='Log in'] | //span[text()='Log in'] | //button[text()='Log in']"
    alternate_log_in_btn = "//span[text()='Log in'] | //div[text()='Log in']"
    incorrect_password = "//div[text()='Sorry, your password was incorrect. Please double-check your password.'] | //div[contains(text(), 'пароль был указан неверно')]"
    email_code_field = "//input[@name='email'] | //input[@name='verificationCode'] | //input[@autocomplete='one-time-code']"
    continue_button = "//span[text()='Continue']/../../../../.. | //button[text()='Continue'] | //div[@role='button' and text()='Continue']"

    alternate_continue_button = "//div[text()='Continue']"
    alternate_email_code_field = "//div[@aria-label='Security code']"
    alternate_submit_button = "//div[text()='Submit']"

    save_session_button = "//button[text()='Save info']"
    alternate_save_session_button = "//span[text()='Save']/../../../../.."
    not_now_button = "//button[text()='Not Now']"

    2fa_link = "https://www.instagram.com/accounts/onetap/?next=%2F"

    cookie_of_interest = "sessionid"

    [selectors.upload]
    new_post_button = "//*[text()='Create']/../../../../../.."
    alternate_post_button = "//span[text()='Post']/../.."

    upload_path = "//input[@type='file']"

    OK = '//button[text()="OK"]'

    next = "//div[text()='Next']"

    select_crop = "//*[text()='Select crop']/../.."
    original_crop = "//*[text()='Original']/../../.."

    description_field = "//div[@aria-label='Write a caption...']"
    location_field = "//input[@placeholder='Add location']"
    mentions_field = "//input[@placeholder='Add collaborators']"

    first_location = "//div[@role='dialog']/div/div/div/div/div/div/button"
    first_mention = "//div[text()='{}']/../../div/label/div/input"
    done_mentions = "//div[text()='Done']"

    post_video = "//div[text()='Share']"

    is_posted = "//div[text()='Reel shared']"


