version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.windows.simple
    restart: always
    volumes:
      - ./media:/app/media
      - ./static:/app/static
      - ./staticfiles:/app/staticfiles
      - ./logs:/app/logs
      # УБИРАЕМ проблемное монтирование db.sqlite3 - база будет создаваться внутри контейнера
      - db_data:/app/db_data
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here-change-this}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1}
      - DOLPHIN_API_TOKEN=${DOLPHIN_API_TOKEN}
      - RUCAPTCHA_API_KEY=${RUCAPTCHA_API_KEY}
      # КРИТИЧНО для Windows Docker
      - DOLPHIN_API_HOST=${DOLPHIN_API_HOST:-http://host.docker.internal:3001}
      # Указываем путь к БД внутри контейнера
      - DATABASE_PATH=/app/db_data/db.sqlite3
    networks:
      - instagram_network
    # Windows server optimizations
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1'
    # ВАЖНО: Доступ к Windows хосту
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  db_data:
    driver: local

networks:
  instagram_network:
    driver: bridge 