version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.windows
    restart: always
    volumes:
      - ./media:/app/media
      - ./db.sqlite3:/app/db.sqlite3
      - ./static:/app/static
      - ./uploader/static:/app/uploader/static
      - ./staticfiles:/app/staticfiles
      - ./prepared_videos:/app/prepared_videos
      # Windows-specific volume for temp files
      - windows_temp:/app/temp
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1,your-windows-server-ip}
      - DOLPHIN_API_TOKEN=${DOLPHIN_API_TOKEN}
      - RUCAPTCHA_API_KEY=${RUCAPTCHA_API_KEY}
      - TFA_API_URL=${TFA_API_URL}
      # Windows Docker host access - CRITICAL для Dolphin Anty
      - DOLPHIN_API_HOST=${DOLPHIN_API_HOST:-http://host.docker.internal:3001}
      # Windows-specific optimizations
      - PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=0
      - PLAYWRIGHT_BROWSERS_PATH=/app/browsers
    networks:
      - instagram_network
    # Windows server optimizations
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2'
        reservations:
          memory: 2G
          cpus: '1'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    # ВАЖНО: Добавляем хост для доступа к Windows хосту
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  windows_temp:
    driver: local

networks:
  instagram_network:
    driver: bridge 